<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Demande extends \App\Entity\Demande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'idDemande', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'nomRecruteur', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'experience', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'remuneration', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'expiration', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'idRecruteur'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'idDemande', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'nomRecruteur', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'experience', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'remuneration', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'expiration', '' . "\0" . 'App\\Entity\\Demande' . "\0" . 'idRecruteur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Demande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdDemande(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdDemande();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDemande', []);

        return parent::getIdDemande();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomRecruteur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomRecruteur', []);

        return parent::getNomRecruteur();
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getExperience(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperience', []);

        return parent::getExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function getRemuneration(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemuneration', []);

        return parent::getRemuneration();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiration(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiration', []);

        return parent::getExpiration();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRecruteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRecruteur', []);

        return parent::getIdRecruteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomRecruteur(?string $nomRecruteur): \App\Entity\Demande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomRecruteur', [$nomRecruteur]);

        return parent::setNomRecruteur($nomRecruteur);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Demande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setExperience(?int $experience): \App\Entity\Demande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExperience', [$experience]);

        return parent::setExperience($experience);
    }

    /**
     * {@inheritDoc}
     */
    public function setRemuneration(?float $remuneration): \App\Entity\Demande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemuneration', [$remuneration]);

        return parent::setRemuneration($remuneration);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(?int $telephone): \App\Entity\Demande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiration(?\DateTime $expiration): \App\Entity\Demande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiration', [$expiration]);

        return parent::setExpiration($expiration);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRecruteur(?\App\Entity\User $idRecruteur): \App\Entity\Demande
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRecruteur', [$idRecruteur]);

        return parent::setIdRecruteur($idRecruteur);
    }

}
