# config/routes.yaml

index:
    path: /
    controller: App\Controller\DefaultController::index

app_stripe:
    path: /stripe
    controller: App\Controller\StripeController::index

product_category_chart:
    path: '/products/chart'
    controller: App\Controller\ProductController::productCategoryChart

chart:
    path: /chart
    controller: App\Controller\ChartController::index

products_search:
    path: /products/view
    controller: App\Controller\ProductsController::view

daten_show:
    path: /daten/9
    controller: App\Controller\DatenController::show
