<?php

namespace ContainerY6bfu5d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YtDAoPlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YtDAoPl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YtDAoPl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demandeRepository' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'posteRepository' => ['privates', 'App\\Repository\\PosteRepository', 'getPosteRepositoryService', true],
        ], [
            'demandeRepository' => 'App\\Repository\\DemandeRepository',
            'entityManager' => '?',
            'paginator' => '?',
            'posteRepository' => 'App\\Repository\\PosteRepository',
        ]);
    }
}
