<?php

namespace ContainerY6bfu5d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GFFFepcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GFFFepc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GFFFepc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demanderep' => ['privates', 'App\\Repository\\DemandeRepository', 'getDemandeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'pdf' => ['services', 'knp_snappy.pdf', 'getKnpSnappy_PdfService', true],
        ], [
            'demanderep' => 'App\\Repository\\DemandeRepository',
            'entityManager' => '?',
            'pdf' => '?',
        ]);
    }
}
