<?php

namespace ContainerY6bfu5d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9ZCX2DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9ZC_x2D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9ZC_x2D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'service' => ['privates', '.errored..service_locator.9ZC_x2D.App\\Entity\\Services', NULL, 'Cannot autowire service ".service_locator.9ZC_x2D": it references class "App\\Entity\\Services" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'service' => 'App\\Entity\\Services',
        ]);
    }
}
