<?php

namespace ContainerY6bfu5d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategories2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yv2_F8f.App\Entity\Categories' shared service.
     *
     * @return \App\Entity\Categories
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yv2_F8f": it references class "App\\Entity\\Categories" but no such service exists.');
    }
}
