<?php

namespace ContainerY6bfu5d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemande2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wyUfPzW.App\Entity\Demande' shared service.
     *
     * @return \App\Entity\Demande
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.wyUfPzW": it references class "App\\Entity\\Demande" but no such service exists.');
    }
}
