<?php

namespace ContainerY6bfu5d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPosteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..jBVc1g.App\Entity\Poste' shared service.
     *
     * @return \App\Entity\Poste
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..jBVc1g": it references class "App\\Entity\\Poste" but no such service exists.');
    }
}
