<?php

namespace ContainerGFzT7PL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__JBVc1gService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..jBVc1g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..jBVc1g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'poste' => ['privates', '.errored..service_locator..jBVc1g.App\\Entity\\Poste', NULL, 'Cannot autowire service ".service_locator..jBVc1g": it references class "App\\Entity\\Poste" but no such service exists.'],
        ], [
            'poste' => 'App\\Entity\\Poste',
        ]);
    }
}
