<?php

namespace ContainerGFzT7PL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WyUfPzWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wyUfPzW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wyUfPzW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'demande' => ['privates', '.errored..service_locator.wyUfPzW.App\\Entity\\Demande', NULL, 'Cannot autowire service ".service_locator.wyUfPzW": it references class "App\\Entity\\Demande" but no such service exists.'],
            'repoP' => ['privates', 'App\\Repository\\PosteRepository', 'getPosteRepositoryService', true],
        ], [
            'demande' => 'App\\Entity\\Demande',
            'repoP' => 'App\\Repository\\PosteRepository',
        ]);
    }
}
