<?php

namespace ContainerGFzT7PL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HxMK5k5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hxMK5k5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hxMK5k5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'pdf' => ['services', 'knp_snappy.pdf', 'getKnpSnappy_PdfService', true],
        ], [
            'entityManager' => '?',
            'pdf' => '?',
        ]);
    }
}
