<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGFzT7PL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGFzT7PL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGFzT7PL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGFzT7PL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGFzT7PL\App_KernelDevDebugContainer([
    'container.build_hash' => 'GFzT7PL',
    'container.build_id' => 'deaa4a88',
    'container.build_time' => 1683133214,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGFzT7PL');
