<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI0B8xSE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI0B8xSE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI0B8xSE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI0B8xSE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI0B8xSE\App_KernelDevDebugContainer([
    'container.build_hash' => 'I0B8xSE',
    'container.build_id' => 'd78bb191',
    'container.build_time' => 1683229088,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI0B8xSE');
